# Generated by Django 4.1.4 on 2022-12-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='meal_time',
            field=models.CharField(default='Dinner', max_length=200, null=True),
        ),
    ]
