# Generated by Django 4.1.4 on 2022-12-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_mealtime_remove_menuitem_meal_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='meal_time',
            field=models.ManyToManyField(related_name='item', to='customer.mealtime'),
        ),
    ]
